# Generated by Django 4.2.16 on 2024-11-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_options_reminder_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
